AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Persist an item to a DynamoDB table from Lambda
Resources:
  AppApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: apigw-api-key
      Description: API key REST API demo

  RootMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AppApi
      ResourceId: !GetAtt AppApi.RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: True
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt LambdaPutDynamoDB.Arn, '/invocations']]

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      ApiStages: 
        - ApiId: !Ref AppApi
          Stage: !Ref Stage
  
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Enabled: True

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - RootMethodGet
    Properties:
      RestApiId: !Ref AppApi
  
  Stage:  
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref AppApi
      DeploymentId: !Ref Deployment

##########################################################################
#   Lambda Function                                                      #
##########################################################################
  LambdaPutDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.create
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoTable
      Events:
        CreateData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AppApi
            Path: /
            Method: POST

  AppFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaPutDynamoDB 
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AppApi}/*/GET/

  LambdaListDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.list
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        ## Read more about SAM Policy templates at:
        ## https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoTable
      Events:
        CreateData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: GET

        
##########################################################################
#   DynamoDB                                                            #
##########################################################################
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
##########################################################################
#   OUTPUTS                                                              #
##########################################################################
  
Outputs:
  LambdCreateFunction:
    Value: !Ref LambdaPutDynamoDB
    Description: LambdaPutDynamoDB function  Arn

  LambdListFunction:
    Value: !Ref LambdaListDynamoDB
    Description: LambdaListDynamoDB function  Arn

  DynamoDbTable:
    Value: !Ref DynamoTable
    Description: DynamoDb Table 

  AppApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
